language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t shmaiter/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true shmaiter/docker-react npm run test